import json

import caveclient
from nglui import statebuilder

from mcp_src.core import mcp_server, session, cave_client
from mcp_src.neuron_types import SceneResult
import urllib.parse


# FIXME - could make more sense to just call this as a function in all query tools, and return scene for each

def build_scene_from_neuron_selection(results_df, x, y, z):
    found_root_ids = [str(int(row['pt_root_id'])) for _, row in results_df.iterrows()]

    seg_source = cave_client.info.segmentation_source()

    viewer = (
        statebuilder.ViewerState(dimensions=[1, 1, 1])
        .add_segmentation_layer(name='3D_Meshes', source=seg_source, segments=found_root_ids)
    )
    state = viewer.to_dict()
    return {"layers": state.get("layers", []), "suggested_position": state.get("position")}

#@mcp_server.tool()
def build_scene_from_memory(memory_reference_id: str) -> SceneResult:
    """
    Takes a memory_reference_id generated by 'search_excitatory_population' or
    'get_downstream_synapses' and generates a 3D structural view.

    Returns a SceneResult with two fields:
    - summary: human-readable description of what was built
    - scene_url: the Neuroglancer URL (present this to the user as a markdown link)
    """
    if memory_reference_id not in session.dataframes:
        return SceneResult(summary="Error: memory reference does not exist or has expired.", scene_url="")

    df = session.dataframes[memory_reference_id]
    target_ids = df['pt_root_id'].tolist()

    em_source = cave_client.info.image_source()
    seg_source = cave_client.info.segmentation_source()

    viewer = statebuilder.ViewerState(dimensions=[4, 4, 40])

    viewer_url = (
        viewer
        .add_image_layer(name='EM_Background', source=em_source)
        .add_segmentation_layer(
            name='Cell_Mesh',
            source=seg_source,
            segments=target_ids
        )
    )

    if 'pt_position' in df.columns:
        viewer_url = viewer_url.add_points(
            data=df,
            point_column='pt_position',
            layer_name='Coordinates',
            description_column='id' if 'id' in df.columns else 'pt_root_id'
        )

    # FIXME - abstract away server URL
    url = viewer_url.to_url(target_url='https://neuroglancer-demo.appspot.com/')
    return SceneResult(
        summary=f"3D scene built with {len(target_ids)} neuron(s).",
        scene_url=url
    )
